### ISSUE TITLE
Missing Python requirements

### ISSUE THREAD

**Issue by zhangysh1995** [midwinter1993/Schnauzer#1]
It seems the requirements file is not updated, could you please add missing dependencies? 

For example:
````
(Schnauzer) zhangysh1995@zhanysh1995-OptiPlex-7060:~/code/fse18$ ./LetsGo settle pbzip2-0.9.4       
Traceback (most recent call last):
  File "./LetsGo", line 45, in <module>
    import matplotlib.pyplot as plt
ImportError: No module named matplotlib.pyplot
````

and then 
````
(Schnauzer) zhangysh1995@zhanysh1995-OptiPlex-7060:~/code/fse18$ ./LetsGo settle pbzip2-0.9.4       
Traceback (most recent call last):
  File "./LetsGo", line 45, in <module>
    import matplotlib.pyplot as plt
  File "/home/zhangysh1995/.local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 115, in <m
odule>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/zhangysh1995/.local/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line
 62, in pylab_setup
    [backend_name], 0)
  File "/home/zhangysh1995/.local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py",
 line 4, in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
  File "/home/zhangysh1995/.local/lib/python2.7/site-packages/matplotlib/backends/tkagg.py", line 5,
 in <module>
    from six.moves import tkinter as Tk
  File "/home/zhangysh1995/.local/lib/python2.7/site-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/home/zhangysh1995/.local/lib/python2.7/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/home/zhangysh1995/.local/lib/python2.7/site-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
    raise ImportError, str(msg) + ', please install the python-tk package'
ImportError: No module named _tkinter, please install the python-tk package

````

**Comment by midwinter1993** [comment]
I have fixed the `requirements.txt` file. Thx :-P
